AWSTemplateFormatVersion: '2010-09-09'

Description: This AWS CloudFormation Template that configures the Container DevSecOps workshop. 


Resources:

  AnchoreVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: container-devsecops-wksp
      TemplateURL: https://container-workshop-test-bucket-1.s3.us-east-2.amazonaws.com/anchore-vpc.yml

  AnchoreStack:
    DependsOn: AnchoreVpcStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: container-devsecops-wksp
      TemplateURL: https://container-workshop-test-bucket-1.s3.us-east-2.amazonaws.com/anchore-fargate.yml

  InitialPipeline:
    DependsOn: AnchoreStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: container-devsecops-wksp
        FailWhen: High
      TemplateURL: https://container-workshop-test-bucket-1.s3.us-east-2.amazonaws.com/pipeline-setup.yml
  

Outputs: {}