version: 0.2

phases: 
  pre_build: 
    commands:
      - apt-get update
      - apt-get install -y clamav
      - freshclam
      - apt-add-repository ppa:duggan/jo --yes
      - apt-get update -q
      - apt-get install jo
      - apt-get install python3-pip
      - pip3 install awscli --upgrade --user
  build: 
    commands:
      - IMAGE="current_app"
      - docker build $CODEBUILD_SRC_DIR_AppSource -t $IMAGE
      - SCAN_RESULTS=$(clamscan -r -i /var/lib/docker || true) 
     
  post_build:
    commands:
      - echo $SCAN_RESULTS
      - JSON_STRING=$(jo -p scanresults="$SCAN_RESULTS" repourl="$CODEBUILD_SOURCE_REPO_URL_AppSource")
      - if echo $SCAN_RESULTS | grep 'FOUND'; then aws lambda invoke --function-name $FUNCTION_ARN --invocation-type RequestResponse --payload "$JSON_STRING" malwareResponse && exit 1; fi
      - echo Build completed on `date`
      
